# File:   Makefile
# Author: Autogenerated
# Date:   2017-10-13
# Descr:  Makefile for game.c


# Definitions.
CC = avr-gcc
CFLAGS = -mmcu=atmega32u2 -Os -Wall -Wstrict-prototypes -Wextra -g -I../../fonts/ -I../../drivers/ -I../../drivers/avr/ -I../../utils/ -I./lib/ -I./
OBJCOPY = avr-objcopy
SIZE = avr-size
DEL = rm


# Default target.
all: game.out


# Compile: create object files from C source files.
game.o: ./game.c ../../drivers/avr/system.h ../../utils/task.h ./lib/board.h ../../drivers/avr/timer.h ./game.h ./lib/snake.h ./lib/input.h
	$(CC) -c $(CFLAGS) $< -o $@

task.o: ../../utils/task.c ../../drivers/avr/system.h ../../drivers/avr/timer.h ../../utils/task.h
	$(CC) -c $(CFLAGS) $< -o $@

timer.o: ../../drivers/avr/timer.c ../../drivers/avr/system.h ../../drivers/avr/timer.h
	$(CC) -c $(CFLAGS) $< -o $@

system.o: ../../drivers/avr/system.c ../../drivers/avr/system.h
	$(CC) -c $(CFLAGS) $< -o $@

board.o: ./lib/board.c ../../drivers/avr/system.h ../../utils/tinygl.h ../../drivers/display.h ../../drivers/avr/pio.h ../../fonts/font3x5_1.h ../../utils/task.h ../../drivers/led.h ./lib/board.h ../../drivers/avr/timer.h ./game.h ../../drivers/ledmat.h ../../utils/font.h
	$(CC) -c $(CFLAGS) $< -o $@

led.o: ../../drivers/led.c ../../drivers/avr/system.h ../../drivers/led.h ../../drivers/avr/pio.h
	$(CC) -c $(CFLAGS) $< -o $@

pio.o: ../../drivers/avr/pio.c ../../drivers/avr/system.h ../../drivers/avr/pio.h
	$(CC) -c $(CFLAGS) $< -o $@

tinygl.o: ../../utils/tinygl.c ../../drivers/avr/system.h ../../drivers/display.h ../../utils/tinygl.h ../../utils/font.h
	$(CC) -c $(CFLAGS) $< -o $@

font.o: ../../utils/font.c ../../drivers/avr/system.h ../../utils/font.h
	$(CC) -c $(CFLAGS) $< -o $@

display.o: ../../drivers/display.c ../../drivers/avr/system.h ../../drivers/display.h ../../drivers/ledmat.h
	$(CC) -c $(CFLAGS) $< -o $@

ledmat.o: ../../drivers/ledmat.c ../../drivers/avr/system.h ../../drivers/avr/pio.h ../../drivers/ledmat.h
	$(CC) -c $(CFLAGS) $< -o $@

snake.o: ./lib/snake.c ../../drivers/avr/system.h ../../utils/task.h ../../drivers/avr/timer.h ./lib/code.h ./game.h ./lib/snake.h
	$(CC) -c $(CFLAGS) $< -o $@

code.o: ./lib/code.c ../../drivers/avr/system.h ../../drivers/avr/ir_uart.h ../../drivers/avr/delay.h ./lib/code.h
	$(CC) -c $(CFLAGS) $< -o $@

ir_uart.o: ../../drivers/avr/ir_uart.c ../../drivers/avr/system.h ../../drivers/avr/pio.h ../../drivers/avr/usart1.h ../../drivers/avr/ir_uart.h ../../drivers/avr/delay.h ../../drivers/avr/timer0.h
	$(CC) -c $(CFLAGS) $< -o $@

timer0.o: ../../drivers/avr/timer0.c ../../drivers/avr/system.h ../../drivers/avr/bits.h ../../drivers/avr/timer0.h ../../drivers/avr/prescale.h
	$(CC) -c $(CFLAGS) $< -o $@

prescale.o: ../../drivers/avr/prescale.c ../../drivers/avr/system.h ../../drivers/avr/prescale.h
	$(CC) -c $(CFLAGS) $< -o $@

usart1.o: ../../drivers/avr/usart1.c ../../drivers/avr/system.h ../../drivers/avr/usart1.h
	$(CC) -c $(CFLAGS) $< -o $@

input.o: ./lib/input.c ../../drivers/avr/system.h ../../drivers/navswitch.h ../../utils/task.h ../../drivers/led.h ../../drivers/avr/timer.h ./game.h ./lib/code.h ../../drivers/avr/delay.h ./lib/input.h
	$(CC) -c $(CFLAGS) $< -o $@

navswitch.o: ../../drivers/navswitch.c ../../drivers/avr/system.h ../../drivers/avr/delay.h ../../drivers/navswitch.h ../../drivers/avr/pio.h
	$(CC) -c $(CFLAGS) $< -o $@

game.out: game.o task.o timer.o system.o board.o led.o pio.o tinygl.o font.o display.o ledmat.o snake.o code.o ir_uart.o timer0.o prescale.o usart1.o input.o navswitch.o
	$(CC) $(CFLAGS) $^ -o $@ -lm
	$(SIZE) $@


# Target: clean project.
.PHONY: clean
clean:
	-$(DEL) *.o *.out *.hex


# Target: program project.
.PHONY: program
program: game.out
	$(OBJCOPY) -O ihex game.out game.hex
	dfu-programmer atmega32u2 erase; dfu-programmer atmega32u2 flash game.hex; dfu-programmer atmega32u2 start

